# Generated by Django 3.2.6 on 2021-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeroShare',
            fields=[
                ('share_mnemonic', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('share_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.FloatField()),
            ],
            options={
                'db_table': 'meroshare',
            },
        ),
    ]
